builds:
  - binary: cptool
    goos:
      - darwin
      - linux
    goarch:
      - 386
      - amd64
      - amd64p32
      - arm
      - armbe
      - arm64
      - arm64be
      - ppc64
      - ppc64le
      - mips
      - mipsle
      - mips64
      - mips64le
      - mips64p32
      - mips64p32le
      - ppc
      - s390
      - s390x
      - sparc
      - sparc64

archive:
  format: tar.gz
  files:
    - LICENSE
    - README.md
    - langs/*
    - config
