#!/bin/bash

CPTOOL_DIR=`dirname $0`

source "$CPTOOL_DIR/util"

print_usage() {
  echo "Compile"
  echo "  compile competitive programming solution."
  echo ""
  echo "Usage: cptool compile [OPTION]... [LANGUAGE] SOLUTION"
  echo ""
  echo "Available commands:"
	echo "  -h --help    Show this help screen."
  echo "  --version    Show version."
  echo "  -d --debug   Compile using debug mode"
  echo ""
}

compile_solution() {
  local debug="$DEBUG"
  local language="$1"
  local solution="$2"

  local lang_folder=`get_language "$language"`
  if [ $? -eq 0 ]; then
    . "$lang_folder/lang.conf"
    if [ -z "$verbose_name" ]; then
      local verbose_name="$name";
    fi
    if [ -z "$extension" ]; then
      local extension="$language"
    fi

    local current_source_code="$solution.$extension"
    if [ ! -f $current_source_code ]; then
      echo_error "Error compiling solution: file $current_source_code not found"
      exit 1
    fi

    local compile_script="$lang_folder/compile"
    if [ $debug = true ]; then
      if [ ! -f "$lang_folder/debugcompile" ]; then
        echo_warning "Warning compiling solution: language doesn't have debug compile script, use default compile instead"
        local debug=false
      else
        local compile_script="$lang_folder/debugcompile"
      fi
    fi

    local DEST=`get_solution_target_path "$debug" "$language" "$solution"`
    if [ $debug = true ]; then
      local DEST="${DEST}_test"
    fi
    local SOURCE="$current_source_code"
    mkdir -p `dirname $DEST`

    if [ "$DEST" -nt "$SOURCE" ]; then
      echo_warning "Skip compiling solution: no change in solution"
      exit 0
    fi

    eval "DEST=\"$DEST\" SOURCE=\"$SOURCE\" $compile_script"
    if [ $? -eq 0 ]; then
      echo_success "Success compiling solution: $solution"
      exit 0
    else
      echo_error "Error compiling solution: compilation script failed"
      exit 1
    fi
  else
    echo_error "Error compiling solution: language definition doesn't exists"
    exit 1
  fi
}

DEFAULT_LANGUAGE="cpp"

DEBUG=false
LANGUAGE=""
SOLUTION=""

parsing_options=true
for arg in "$@"
do
  if [ $parsing_options = true ]; then
    if [ $arg = "-h" ] || [ $arg = "--help" ]; then
      print_usage
      exit $?
    elif [ $arg = "--version" ]; then
      print_version
      exit $?
    elif [ $arg = "-d" ] || [ $arg = "--debug" ]; then
      DEBUG=true
    else
      parsing_options=false
      LANGUAGE=$arg
    fi
  elif [ -z "$SOLUTION" ]; then
    SOLUTION=$arg
  else
    print_usage
    exit 1
  fi
done

if [ -z "$LANGUAGE" ]; then
  echo_error "Error: please specify solution name."
  print_usage
  exit 1
elif [ -z "$SOLUTION" ]; then
  SOLUTION="$LANGUAGE"
  LANGUAGE="$DEFAULT_LANGUAGE"
fi

compile_solution "$LANGUAGE" "$SOLUTION"
