#!/bin/bash

CPTOOL_DIR=`dirname $0`

source "$CPTOOL_DIR/util"

print_usage() {
  echo "Run"
  echo "  run competitive programming solution."
  echo ""
  echo "Usage: cptool run [OPTION]... [LANGUAGE] SOLUTION"
  echo ""
  echo "Available commands:"
  echo "  -h --help    Show this help screen."
  echo "  --version    Show version."
  echo "  --hide-time  Hide time indicator"
  echo ""
}

run_solution() {
  local hide_time="$1"
  local language="$2"
  local solution="$3"

  $CPTOOL_DIR/compile "$language" "$solution"
  if [ $? -ne 0 ]; then
    exit $?
  fi

  local lang_folder=`get_language "$language"`
  if [ $? -eq 0 ]; then
    source "$lang_folder/lang.conf"
    if [ -z "$verbose_name" ]; then
      local verbose_name="$name";
    fi
    if [ -z "$extension" ]; then
      local extension="$language"
    fi

    local PROGRAM=".cptool/$solution"
    if [ ! -f $PROGRAM ]; then
      echo_error "Error running solution: file $PROGRAM doesn't exists"
      exit 1
    fi

    if [ $hide_time = true ]; then
      eval "PROGRAM=\"$PROGRAM\" \"$lang_folder/run\""
    else
      eval "time PROGRAM=\"$PROGRAM\" \"$lang_folder/run\""
    fi

    if [ $? -eq 0 ]; then
      echo_success "Success running solution: $solution"
      exit 0
    else
      echo_error "Error running solution: run script failed"
      exit 1
    fi

  else
    echo_error "Error running solution: language definition doesn't exists"
    exit 1
  fi
}

DEFAULT_LANGUAGE="cpp"

HIDE_TIME=false
LANGUAGE=""
SOLUTION=""

parsing_options=true
for arg in "$@"
do
  if [ $parsing_options = true ]; then
    if [ $arg = "-h" ] || [ $arg = "--help" ]; then
      print_usage
      exit $?
    elif [ $arg = "--version" ]; then
      print_version
      exit $?
    elif [ $arg = "--hide-time" ]; then
      HIDE_TIME=true
    else
      parsing_options=false
      LANGUAGE=$arg
    fi
  elif [ -z "$SOLUTION" ]; then
    SOLUTION=$arg
  else
    print_usage
    exit 1
  fi
done

if [ -z "$LANGUAGE" ]; then
  echo "Error: please specify solution name."
  print_usage
  exit 1
elif [ -z "$SOLUTION" ]; then
  SOLUTION="$LANGUAGE"
  LANGUAGE="$DEFAULT_LANGUAGE"
fi

run_solution $HIDE_TIME $LANGUAGE $SOLUTION
