#!/bin/bash

CPTOOL_DIR=`dirname $0`

get_version() {
  cat "$CPTOOL_DIR/VERSION"
}

print_version() {
  echo v`get_version`
}

print_color_error() {
  printf "\033[0;31m`echo "$@"`\033[0m"
}

print_color_success() { 
  printf "\033[0;32m`echo "$@"`\033[0m" 
}

print_color_warning() { 
  printf "\033[0;33m`echo "$@"`\033[0m"
}

print_color_info() {
  printf "\033[0;34m`echo "$@"`\033[0m"
}

show_error() {
  >&2 print_color_error "[  Error  ] "
  >&2 echo $@
}

show_success() {
  >&2 print_color_success "[ Success ] "
  >&2 echo $@
}

show_warning() {
  >&2 print_color_warning "[ Warning ] "
  >&2 echo $@
}

show_info() {
  >&2 print_color_info "[  Info   ] "
  >&2 echo $@
}

is_folder_language() {
  local folder=$1
  if [ -f "$folder/lang.conf" ] && [ -f "$folder/compile" ] && [ -f "$folder/run" ]; then
    return 0
  else
    return 1
  fi
}

get_solution_target_path() {
  local debug="$1"
  local lang="$2"
  local solution="$3"
  if [ $debug = true ]; then
    echo ".cptool/programs/$solution/${lang}_debug"
  else
    echo ".cptool/programs/$solution/$lang"
  fi
}

get_solution_test_path() {
  local lang="$1"
  local solution="$2"
  local test="$3"
  echo ".cptool/tests/$solution/$lang/$test.out"
}

get_language() {
  local lang=$1
  for lang_folder in "$CPTOOL_DIR"/langs/* ~/.cptool/langs/* .cptool/langs/*
  do
    local lang_name=`basename "$lang_folder"`
    is_folder_language "$lang_folder"
    local is_language=$?
    if [ "$lang" = "$lang_name" ] && [ $is_language -eq 0 ]; then
      echo "$lang_folder"
      return 0
    fi
  done
  return 1
}
